from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def write_json_report(data: dict[str, Any], destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_html_report(data: dict[str, Any], destination: Path, title: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    findings = data.get("findings") or data.get("postflight", {}).get("findings", [])
    rows = "".join(
        "<tr>"
        f"<td><span class='severity {html.escape(str(item['severity']))}'>"
        f"{html.escape(str(item['severity']))}</span></td>"
        f"<td><code>{html.escape(str(item['code']))}</code></td>"
        f"<td>{html.escape(str(item['message']))}</td>"
        f"<td>{html.escape(str(item.get('page') or '—'))}</td>"
        "</tr>"
        for item in findings
    )
    body = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
:root {{ color-scheme: light dark; font-family: system-ui, sans-serif; }}
body {{ max-width: 1100px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }}
header {{ border-bottom: 4px solid #1f6f78; margin-bottom: 2rem; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border-bottom: 1px solid #8886; padding: .7rem; text-align: left; vertical-align: top; }}
.severity {{ border-radius: 999px; padding: .2rem .55rem; font-weight: 700; }}
.error {{ background: #8b1e1e; color: white; }}
.warning {{ background: #a15c00; color: white; }}
.info {{ background: #1f6f78; color: white; }}
pre {{ overflow: auto; background: #7772; padding: 1rem; border-radius: .5rem; }}
</style>
</head>
<body>
<header><h1>{html.escape(title)}</h1><p>Generated by Print Color Preflight.</p></header>
<h2>Findings</h2>
<table><thead><tr><th>Severity</th><th>Code</th><th>Finding</th><th>Page</th></tr></thead>
<tbody>{rows}</tbody></table>
<h2>Complete machine-readable record</h2>
<pre>{html.escape(json.dumps(data, indent=2, ensure_ascii=False))}</pre>
</body>
</html>
"""
    destination.write_text(body, encoding="utf-8")
